[build]
  command = "npm run build"
  publish = "build"
  base = "frontend"

[build.environment]
  NODE_VERSION = "18"
  CI = "false"

# SPA için redirect
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
